"""CBOR tags registry for Blockchain Commons projects.

Defines tag constants and registration helpers corresponding to the Rust
`bc-tags` crate. The module extends `dcbor`'s registry with Blockchain
Commons tag assignments, including deprecated aliases for compatibility.
"""

from __future__ import annotations

from dcbor import (
    Tag,
    TagValue,
    TagsStore,
    register_tags_in as register_dcbor_tags_in,
    with_tags,
    with_tags_mut,
)

TAG_URI: TagValue = 32
TAG_NAME_URI = "url"

TAG_UUID: TagValue = 37
TAG_NAME_UUID = "uuid"

TAG_ENCODED_CBOR: TagValue = 24
TAG_NAME_ENCODED_CBOR = "encoded-cbor"

TAG_ENVELOPE: TagValue = 200
TAG_NAME_ENVELOPE = "envelope"

TAG_LEAF: TagValue = 201
TAG_NAME_LEAF = "leaf"

TAG_JSON: TagValue = 262
TAG_NAME_JSON = "json"

TAG_KNOWN_VALUE: TagValue = 40000
TAG_NAME_KNOWN_VALUE = "known-value"

TAG_DIGEST: TagValue = 40001
TAG_NAME_DIGEST = "digest"

TAG_ENCRYPTED: TagValue = 40002
TAG_NAME_ENCRYPTED = "encrypted"

TAG_COMPRESSED: TagValue = 40003
TAG_NAME_COMPRESSED = "compressed"

TAG_REQUEST: TagValue = 40004
TAG_NAME_REQUEST = "request"

TAG_RESPONSE: TagValue = 40005
TAG_NAME_RESPONSE = "response"

TAG_FUNCTION: TagValue = 40006
TAG_NAME_FUNCTION = "function"

TAG_PARAMETER: TagValue = 40007
TAG_NAME_PARAMETER = "parameter"

TAG_PLACEHOLDER: TagValue = 40008
TAG_NAME_PLACEHOLDER = "placeholder"

TAG_REPLACEMENT: TagValue = 40009
TAG_NAME_REPLACEMENT = "replacement"

TAG_X25519_PRIVATE_KEY: TagValue = 40010
TAG_NAME_X25519_PRIVATE_KEY = "agreement-private-key"

TAG_X25519_PUBLIC_KEY: TagValue = 40011
TAG_NAME_X25519_PUBLIC_KEY = "agreement-public-key"

TAG_ARID: TagValue = 40012
TAG_NAME_ARID = "arid"

TAG_PRIVATE_KEYS: TagValue = 40013
TAG_NAME_PRIVATE_KEYS = "crypto-prvkeys"

TAG_NONCE: TagValue = 40014
TAG_NAME_NONCE = "nonce"

TAG_PASSWORD: TagValue = 40015
TAG_NAME_PASSWORD = "password"

TAG_PRIVATE_KEY_BASE: TagValue = 40016
TAG_NAME_PRIVATE_KEY_BASE = "crypto-prvkey-base"

TAG_PUBLIC_KEYS: TagValue = 40017
TAG_NAME_PUBLIC_KEYS = "crypto-pubkeys"

TAG_SALT: TagValue = 40018
TAG_NAME_SALT = "salt"

TAG_SEALED_MESSAGE: TagValue = 40019
TAG_NAME_SEALED_MESSAGE = "crypto-sealed"

TAG_SIGNATURE: TagValue = 40020
TAG_NAME_SIGNATURE = "signature"

TAG_SIGNING_PRIVATE_KEY: TagValue = 40021
TAG_NAME_SIGNING_PRIVATE_KEY = "signing-private-key"

TAG_SIGNING_PUBLIC_KEY: TagValue = 40022
TAG_NAME_SIGNING_PUBLIC_KEY = "signing-public-key"

TAG_SYMMETRIC_KEY: TagValue = 40023
TAG_NAME_SYMMETRIC_KEY = "crypto-key"

TAG_XID: TagValue = 40024
TAG_NAME_XID = "xid"

TAG_REFERENCE: TagValue = 40025
TAG_NAME_REFERENCE = "reference"

TAG_EVENT: TagValue = 40026
TAG_NAME_EVENT = "event"

TAG_ENCRYPTED_KEY: TagValue = 40027
TAG_NAME_ENCRYPTED_KEY = "encrypted-key"

TAG_MLKEM_PRIVATE_KEY: TagValue = 40100
TAG_NAME_MLKEM_PRIVATE_KEY = "mlkem-private-key"

TAG_MLKEM_PUBLIC_KEY: TagValue = 40101
TAG_NAME_MLKEM_PUBLIC_KEY = "mlkem-public-key"

TAG_MLKEM_CIPHERTEXT: TagValue = 40102
TAG_NAME_MLKEM_CIPHERTEXT = "mlkem-ciphertext"

TAG_MLDSA_PRIVATE_KEY: TagValue = 40103
TAG_NAME_MLDSA_PRIVATE_KEY = "mldsa-private-key"

TAG_MLDSA_PUBLIC_KEY: TagValue = 40104
TAG_NAME_MLDSA_PUBLIC_KEY = "mldsa-public-key"

TAG_MLDSA_SIGNATURE: TagValue = 40105
TAG_NAME_MLDSA_SIGNATURE = "mldsa-signature"

TAG_SEED: TagValue = 40300
TAG_NAME_SEED = "seed"

TAG_HDKEY: TagValue = 40303
TAG_NAME_HDKEY = "hdkey"

TAG_DERIVATION_PATH: TagValue = 40304
TAG_NAME_DERIVATION_PATH = "keypath"

TAG_USE_INFO: TagValue = 40305
TAG_NAME_USE_INFO = "coin-info"

TAG_EC_KEY: TagValue = 40306
TAG_NAME_EC_KEY = "eckey"

TAG_ADDRESS: TagValue = 40307
TAG_NAME_ADDRESS = "address"

TAG_OUTPUT_DESCRIPTOR: TagValue = 40308
TAG_NAME_OUTPUT_DESCRIPTOR = "output-descriptor"

TAG_SSKR_SHARE: TagValue = 40309
TAG_NAME_SSKR_SHARE = "sskr"

TAG_PSBT: TagValue = 40310
TAG_NAME_PSBT = "psbt"

TAG_ACCOUNT_DESCRIPTOR: TagValue = 40311
TAG_NAME_ACCOUNT_DESCRIPTOR = "account-descriptor"

TAG_SSH_TEXT_PRIVATE_KEY: TagValue = 40800
TAG_NAME_SSH_TEXT_PRIVATE_KEY = "ssh-private"

TAG_SSH_TEXT_PUBLIC_KEY: TagValue = 40801
TAG_NAME_SSH_TEXT_PUBLIC_KEY = "ssh-public"

TAG_SSH_TEXT_SIGNATURE: TagValue = 40802
TAG_NAME_SSH_TEXT_SIGNATURE = "ssh-signature"

TAG_SSH_TEXT_CERTIFICATE: TagValue = 40803
TAG_NAME_SSH_TEXT_CERTIFICATE = "ssh-certificate"

TAG_PROVENANCE_MARK: TagValue = 1347571542
TAG_NAME_PROVENANCE_MARK = "provenance"

TAG_SEED_V1: TagValue = 300
TAG_NAME_SEED_V1 = "crypto-seed"

TAG_EC_KEY_V1: TagValue = 306
TAG_NAME_EC_KEY_V1 = "crypto-eckey"

TAG_SSKR_SHARE_V1: TagValue = 309
TAG_NAME_SSKR_SHARE_V1 = "crypto-sskr"

TAG_HDKEY_V1: TagValue = 303
TAG_NAME_HDKEY_V1 = "crypto-hdkey"

TAG_DERIVATION_PATH_V1: TagValue = 304
TAG_NAME_DERIVATION_PATH_V1 = "crypto-keypath"

TAG_USE_INFO_V1: TagValue = 305
TAG_NAME_USE_INFO_V1 = "crypto-coin-info"

TAG_OUTPUT_DESCRIPTOR_V1: TagValue = 307
TAG_NAME_OUTPUT_DESCRIPTOR_V1 = "crypto-output"

TAG_PSBT_V1: TagValue = 310
TAG_NAME_PSBT_V1 = "crypto-psbt"

TAG_ACCOUNT_V1: TagValue = 311
TAG_NAME_ACCOUNT_V1 = "crypto-account"

TAG_OUTPUT_SCRIPT_HASH: TagValue = 400
TAG_NAME_OUTPUT_SCRIPT_HASH = "output-script-hash"

TAG_OUTPUT_WITNESS_SCRIPT_HASH: TagValue = 401
TAG_NAME_OUTPUT_WITNESS_SCRIPT_HASH = "output-witness-script-hash"

TAG_OUTPUT_PUBLIC_KEY: TagValue = 402
TAG_NAME_OUTPUT_PUBLIC_KEY = "output-public-key"

TAG_OUTPUT_PUBLIC_KEY_HASH: TagValue = 403
TAG_NAME_OUTPUT_PUBLIC_KEY_HASH = "output-public-key-hash"

TAG_OUTPUT_WITNESS_PUBLIC_KEY_HASH: TagValue = 404
TAG_NAME_OUTPUT_WITNESS_PUBLIC_KEY_HASH = "output-witness-public-key-hash"

TAG_OUTPUT_COMBO: TagValue = 405
TAG_NAME_OUTPUT_COMBO = "output-combo"

TAG_OUTPUT_MULTISIG: TagValue = 406
TAG_NAME_OUTPUT_MULTISIG = "output-multisig"

TAG_OUTPUT_SORTED_MULTISIG: TagValue = 407
TAG_NAME_OUTPUT_SORTED_MULTISIG = "output-sorted-multisig"

TAG_OUTPUT_RAW_SCRIPT: TagValue = 408
TAG_NAME_OUTPUT_RAW_SCRIPT = "output-raw-script"

TAG_OUTPUT_TAPROOT: TagValue = 409
TAG_NAME_OUTPUT_TAPROOT = "output-taproot"

TAG_OUTPUT_COSIGNER: TagValue = 410
TAG_NAME_OUTPUT_COSIGNER = "output-cosigner"

_BC_TAGS: list[Tag] = [
    Tag(TAG_URI, TAG_NAME_URI),
    Tag(TAG_UUID, TAG_NAME_UUID),
    Tag(TAG_ENCODED_CBOR, TAG_NAME_ENCODED_CBOR),
    Tag(TAG_ENVELOPE, TAG_NAME_ENVELOPE),
    Tag(TAG_LEAF, TAG_NAME_LEAF),
    Tag(TAG_JSON, TAG_NAME_JSON),
    Tag(TAG_KNOWN_VALUE, TAG_NAME_KNOWN_VALUE),
    Tag(TAG_DIGEST, TAG_NAME_DIGEST),
    Tag(TAG_ENCRYPTED, TAG_NAME_ENCRYPTED),
    Tag(TAG_COMPRESSED, TAG_NAME_COMPRESSED),
    Tag(TAG_REQUEST, TAG_NAME_REQUEST),
    Tag(TAG_RESPONSE, TAG_NAME_RESPONSE),
    Tag(TAG_FUNCTION, TAG_NAME_FUNCTION),
    Tag(TAG_PARAMETER, TAG_NAME_PARAMETER),
    Tag(TAG_PLACEHOLDER, TAG_NAME_PLACEHOLDER),
    Tag(TAG_REPLACEMENT, TAG_NAME_REPLACEMENT),
    Tag(TAG_EVENT, TAG_NAME_EVENT),
    Tag(TAG_SEED_V1, TAG_NAME_SEED_V1),
    Tag(TAG_EC_KEY_V1, TAG_NAME_EC_KEY_V1),
    Tag(TAG_SSKR_SHARE_V1, TAG_NAME_SSKR_SHARE_V1),
    Tag(TAG_SEED, TAG_NAME_SEED),
    Tag(TAG_EC_KEY, TAG_NAME_EC_KEY),
    Tag(TAG_SSKR_SHARE, TAG_NAME_SSKR_SHARE),
    Tag(TAG_X25519_PRIVATE_KEY, TAG_NAME_X25519_PRIVATE_KEY),
    Tag(TAG_X25519_PUBLIC_KEY, TAG_NAME_X25519_PUBLIC_KEY),
    Tag(TAG_ARID, TAG_NAME_ARID),
    Tag(TAG_PRIVATE_KEYS, TAG_NAME_PRIVATE_KEYS),
    Tag(TAG_NONCE, TAG_NAME_NONCE),
    Tag(TAG_PASSWORD, TAG_NAME_PASSWORD),
    Tag(TAG_PRIVATE_KEY_BASE, TAG_NAME_PRIVATE_KEY_BASE),
    Tag(TAG_PUBLIC_KEYS, TAG_NAME_PUBLIC_KEYS),
    Tag(TAG_SALT, TAG_NAME_SALT),
    Tag(TAG_SEALED_MESSAGE, TAG_NAME_SEALED_MESSAGE),
    Tag(TAG_SIGNATURE, TAG_NAME_SIGNATURE),
    Tag(TAG_SIGNING_PRIVATE_KEY, TAG_NAME_SIGNING_PRIVATE_KEY),
    Tag(TAG_SIGNING_PUBLIC_KEY, TAG_NAME_SIGNING_PUBLIC_KEY),
    Tag(TAG_SYMMETRIC_KEY, TAG_NAME_SYMMETRIC_KEY),
    Tag(TAG_XID, TAG_NAME_XID),
    Tag(TAG_REFERENCE, TAG_NAME_REFERENCE),
    Tag(TAG_ENCRYPTED_KEY, TAG_NAME_ENCRYPTED_KEY),
    Tag(TAG_MLKEM_PRIVATE_KEY, TAG_NAME_MLKEM_PRIVATE_KEY),
    Tag(TAG_MLKEM_PUBLIC_KEY, TAG_NAME_MLKEM_PUBLIC_KEY),
    Tag(TAG_MLKEM_CIPHERTEXT, TAG_NAME_MLKEM_CIPHERTEXT),
    Tag(TAG_MLDSA_PRIVATE_KEY, TAG_NAME_MLDSA_PRIVATE_KEY),
    Tag(TAG_MLDSA_PUBLIC_KEY, TAG_NAME_MLDSA_PUBLIC_KEY),
    Tag(TAG_MLDSA_SIGNATURE, TAG_NAME_MLDSA_SIGNATURE),
    Tag(TAG_HDKEY_V1, TAG_NAME_HDKEY_V1),
    Tag(TAG_DERIVATION_PATH_V1, TAG_NAME_DERIVATION_PATH_V1),
    Tag(TAG_USE_INFO_V1, TAG_NAME_USE_INFO_V1),
    Tag(TAG_OUTPUT_DESCRIPTOR_V1, TAG_NAME_OUTPUT_DESCRIPTOR_V1),
    Tag(TAG_PSBT_V1, TAG_NAME_PSBT_V1),
    Tag(TAG_ACCOUNT_V1, TAG_NAME_ACCOUNT_V1),
    Tag(TAG_HDKEY, TAG_NAME_HDKEY),
    Tag(TAG_DERIVATION_PATH, TAG_NAME_DERIVATION_PATH),
    Tag(TAG_USE_INFO, TAG_NAME_USE_INFO),
    Tag(TAG_ADDRESS, TAG_NAME_ADDRESS),
    Tag(TAG_OUTPUT_DESCRIPTOR, TAG_NAME_OUTPUT_DESCRIPTOR),
    Tag(TAG_PSBT, TAG_NAME_PSBT),
    Tag(TAG_ACCOUNT_DESCRIPTOR, TAG_NAME_ACCOUNT_DESCRIPTOR),
    Tag(TAG_SSH_TEXT_PRIVATE_KEY, TAG_NAME_SSH_TEXT_PRIVATE_KEY),
    Tag(TAG_SSH_TEXT_PUBLIC_KEY, TAG_NAME_SSH_TEXT_PUBLIC_KEY),
    Tag(TAG_SSH_TEXT_SIGNATURE, TAG_NAME_SSH_TEXT_SIGNATURE),
    Tag(TAG_SSH_TEXT_CERTIFICATE, TAG_NAME_SSH_TEXT_CERTIFICATE),
    Tag(TAG_OUTPUT_SCRIPT_HASH, TAG_NAME_OUTPUT_SCRIPT_HASH),
    Tag(TAG_OUTPUT_WITNESS_SCRIPT_HASH, TAG_NAME_OUTPUT_WITNESS_SCRIPT_HASH),
    Tag(TAG_OUTPUT_PUBLIC_KEY, TAG_NAME_OUTPUT_PUBLIC_KEY),
    Tag(TAG_OUTPUT_PUBLIC_KEY_HASH, TAG_NAME_OUTPUT_PUBLIC_KEY_HASH),
    Tag(TAG_OUTPUT_WITNESS_PUBLIC_KEY_HASH, TAG_NAME_OUTPUT_WITNESS_PUBLIC_KEY_HASH),
    Tag(TAG_OUTPUT_COMBO, TAG_NAME_OUTPUT_COMBO),
    Tag(TAG_OUTPUT_MULTISIG, TAG_NAME_OUTPUT_MULTISIG),
    Tag(TAG_OUTPUT_SORTED_MULTISIG, TAG_NAME_OUTPUT_SORTED_MULTISIG),
    Tag(TAG_OUTPUT_RAW_SCRIPT, TAG_NAME_OUTPUT_RAW_SCRIPT),
    Tag(TAG_OUTPUT_TAPROOT, TAG_NAME_OUTPUT_TAPROOT),
    Tag(TAG_OUTPUT_COSIGNER, TAG_NAME_OUTPUT_COSIGNER),
    Tag(TAG_PROVENANCE_MARK, TAG_NAME_PROVENANCE_MARK),
]


def register_tags_in(tags_store: TagsStore) -> None:
    """Register all `dcbor` and Blockchain Commons tags into `tags_store`."""
    register_dcbor_tags_in(tags_store)
    tags_store.insert_all(_BC_TAGS)


def register_tags() -> None:
    """Register all `dcbor` and Blockchain Commons tags in the global store."""
    # Ensure the global store is initialized before taking the mutable lock.
    with_tags(lambda _: None)
    with_tags_mut(lambda tags_store: register_tags_in(tags_store))


__all__ = [
    "TAG_URI",
    "TAG_NAME_URI",
    "TAG_UUID",
    "TAG_NAME_UUID",
    "TAG_ENCODED_CBOR",
    "TAG_NAME_ENCODED_CBOR",
    "TAG_ENVELOPE",
    "TAG_NAME_ENVELOPE",
    "TAG_LEAF",
    "TAG_NAME_LEAF",
    "TAG_JSON",
    "TAG_NAME_JSON",
    "TAG_KNOWN_VALUE",
    "TAG_NAME_KNOWN_VALUE",
    "TAG_DIGEST",
    "TAG_NAME_DIGEST",
    "TAG_ENCRYPTED",
    "TAG_NAME_ENCRYPTED",
    "TAG_COMPRESSED",
    "TAG_NAME_COMPRESSED",
    "TAG_REQUEST",
    "TAG_NAME_REQUEST",
    "TAG_RESPONSE",
    "TAG_NAME_RESPONSE",
    "TAG_FUNCTION",
    "TAG_NAME_FUNCTION",
    "TAG_PARAMETER",
    "TAG_NAME_PARAMETER",
    "TAG_PLACEHOLDER",
    "TAG_NAME_PLACEHOLDER",
    "TAG_REPLACEMENT",
    "TAG_NAME_REPLACEMENT",
    "TAG_X25519_PRIVATE_KEY",
    "TAG_NAME_X25519_PRIVATE_KEY",
    "TAG_X25519_PUBLIC_KEY",
    "TAG_NAME_X25519_PUBLIC_KEY",
    "TAG_ARID",
    "TAG_NAME_ARID",
    "TAG_PRIVATE_KEYS",
    "TAG_NAME_PRIVATE_KEYS",
    "TAG_NONCE",
    "TAG_NAME_NONCE",
    "TAG_PASSWORD",
    "TAG_NAME_PASSWORD",
    "TAG_PRIVATE_KEY_BASE",
    "TAG_NAME_PRIVATE_KEY_BASE",
    "TAG_PUBLIC_KEYS",
    "TAG_NAME_PUBLIC_KEYS",
    "TAG_SALT",
    "TAG_NAME_SALT",
    "TAG_SEALED_MESSAGE",
    "TAG_NAME_SEALED_MESSAGE",
    "TAG_SIGNATURE",
    "TAG_NAME_SIGNATURE",
    "TAG_SIGNING_PRIVATE_KEY",
    "TAG_NAME_SIGNING_PRIVATE_KEY",
    "TAG_SIGNING_PUBLIC_KEY",
    "TAG_NAME_SIGNING_PUBLIC_KEY",
    "TAG_SYMMETRIC_KEY",
    "TAG_NAME_SYMMETRIC_KEY",
    "TAG_XID",
    "TAG_NAME_XID",
    "TAG_REFERENCE",
    "TAG_NAME_REFERENCE",
    "TAG_EVENT",
    "TAG_NAME_EVENT",
    "TAG_ENCRYPTED_KEY",
    "TAG_NAME_ENCRYPTED_KEY",
    "TAG_MLKEM_PRIVATE_KEY",
    "TAG_NAME_MLKEM_PRIVATE_KEY",
    "TAG_MLKEM_PUBLIC_KEY",
    "TAG_NAME_MLKEM_PUBLIC_KEY",
    "TAG_MLKEM_CIPHERTEXT",
    "TAG_NAME_MLKEM_CIPHERTEXT",
    "TAG_MLDSA_PRIVATE_KEY",
    "TAG_NAME_MLDSA_PRIVATE_KEY",
    "TAG_MLDSA_PUBLIC_KEY",
    "TAG_NAME_MLDSA_PUBLIC_KEY",
    "TAG_MLDSA_SIGNATURE",
    "TAG_NAME_MLDSA_SIGNATURE",
    "TAG_SEED",
    "TAG_NAME_SEED",
    "TAG_HDKEY",
    "TAG_NAME_HDKEY",
    "TAG_DERIVATION_PATH",
    "TAG_NAME_DERIVATION_PATH",
    "TAG_USE_INFO",
    "TAG_NAME_USE_INFO",
    "TAG_EC_KEY",
    "TAG_NAME_EC_KEY",
    "TAG_ADDRESS",
    "TAG_NAME_ADDRESS",
    "TAG_OUTPUT_DESCRIPTOR",
    "TAG_NAME_OUTPUT_DESCRIPTOR",
    "TAG_SSKR_SHARE",
    "TAG_NAME_SSKR_SHARE",
    "TAG_PSBT",
    "TAG_NAME_PSBT",
    "TAG_ACCOUNT_DESCRIPTOR",
    "TAG_NAME_ACCOUNT_DESCRIPTOR",
    "TAG_SSH_TEXT_PRIVATE_KEY",
    "TAG_NAME_SSH_TEXT_PRIVATE_KEY",
    "TAG_SSH_TEXT_PUBLIC_KEY",
    "TAG_NAME_SSH_TEXT_PUBLIC_KEY",
    "TAG_SSH_TEXT_SIGNATURE",
    "TAG_NAME_SSH_TEXT_SIGNATURE",
    "TAG_SSH_TEXT_CERTIFICATE",
    "TAG_NAME_SSH_TEXT_CERTIFICATE",
    "TAG_PROVENANCE_MARK",
    "TAG_NAME_PROVENANCE_MARK",
    "TAG_SEED_V1",
    "TAG_NAME_SEED_V1",
    "TAG_EC_KEY_V1",
    "TAG_NAME_EC_KEY_V1",
    "TAG_SSKR_SHARE_V1",
    "TAG_NAME_SSKR_SHARE_V1",
    "TAG_HDKEY_V1",
    "TAG_NAME_HDKEY_V1",
    "TAG_DERIVATION_PATH_V1",
    "TAG_NAME_DERIVATION_PATH_V1",
    "TAG_USE_INFO_V1",
    "TAG_NAME_USE_INFO_V1",
    "TAG_OUTPUT_DESCRIPTOR_V1",
    "TAG_NAME_OUTPUT_DESCRIPTOR_V1",
    "TAG_PSBT_V1",
    "TAG_NAME_PSBT_V1",
    "TAG_ACCOUNT_V1",
    "TAG_NAME_ACCOUNT_V1",
    "TAG_OUTPUT_SCRIPT_HASH",
    "TAG_NAME_OUTPUT_SCRIPT_HASH",
    "TAG_OUTPUT_WITNESS_SCRIPT_HASH",
    "TAG_NAME_OUTPUT_WITNESS_SCRIPT_HASH",
    "TAG_OUTPUT_PUBLIC_KEY",
    "TAG_NAME_OUTPUT_PUBLIC_KEY",
    "TAG_OUTPUT_PUBLIC_KEY_HASH",
    "TAG_NAME_OUTPUT_PUBLIC_KEY_HASH",
    "TAG_OUTPUT_WITNESS_PUBLIC_KEY_HASH",
    "TAG_NAME_OUTPUT_WITNESS_PUBLIC_KEY_HASH",
    "TAG_OUTPUT_COMBO",
    "TAG_NAME_OUTPUT_COMBO",
    "TAG_OUTPUT_MULTISIG",
    "TAG_NAME_OUTPUT_MULTISIG",
    "TAG_OUTPUT_SORTED_MULTISIG",
    "TAG_NAME_OUTPUT_SORTED_MULTISIG",
    "TAG_OUTPUT_RAW_SCRIPT",
    "TAG_NAME_OUTPUT_RAW_SCRIPT",
    "TAG_OUTPUT_TAPROOT",
    "TAG_NAME_OUTPUT_TAPROOT",
    "TAG_OUTPUT_COSIGNER",
    "TAG_NAME_OUTPUT_COSIGNER",
    "register_tags",
    "register_tags_in",
]
