using System.Buffers.Binary;

namespace BlockchainCommons.BCRand;

/// <summary>
/// A random number generator that can be used as a source of deterministic
/// pseudo-randomness for testing purposes.
/// </summary>
/// <remarks>
/// Uses Xoshiro256** internally. Not cryptographically secure.
/// </remarks>
public sealed class SeededRandomNumberGenerator : IRandomNumberGenerator
{
    private static readonly ulong[] FakeSeed =
    [
        17295166580085024720,
        422929670265678780,
        5577237070365765850,
        7953171132032326923
    ];

    private readonly Xoshiro256StarStar _rng;

    /// <summary>
    /// Creates a new seeded random number generator.
    /// </summary>
    /// <param name="seed">
    /// A 256-bit seed represented as an array of 4 unsigned 64-bit integers.
    /// The seed should not have any obvious patterns (such as all zeroes or all ones)
    /// for the output distribution to appear random.
    /// </param>
    /// <remarks>
    /// This generator is not cryptographically secure and should only be used
    /// for testing purposes.
    /// </remarks>
    public SeededRandomNumberGenerator(ulong[] seed)
    {
        ArgumentNullException.ThrowIfNull(seed);
        _rng = CreateRngFromSeed(seed);
    }

    /// <summary>
    /// Creates a new seeded random number generator.
    /// </summary>
    /// <param name="seed">
    /// A 256-bit seed represented as a span of 4 unsigned 64-bit integers.
    /// </param>
    public SeededRandomNumberGenerator(ReadOnlySpan<ulong> seed)
    {
        _rng = CreateRngFromSeed(seed);
    }

    private static Xoshiro256StarStar CreateRngFromSeed(ReadOnlySpan<ulong> seed)
    {
        if (seed.Length != 4)
            throw new ArgumentException("Seed must contain exactly 4 elements.", nameof(seed));

        Span<byte> seedBytes = stackalloc byte[32];
        for (int i = 0; i < 4; i++)
            BinaryPrimitives.WriteUInt64LittleEndian(seedBytes.Slice(i * 8, 8), seed[i]);

        return new Xoshiro256StarStar(seedBytes);
    }

    public uint NextUInt32() => (uint)NextUInt64();

    public ulong NextUInt64() => _rng.NextUInt64();

    /// <summary>
    /// Returns an array of random bytes, generated byte-by-byte from NextUInt64().
    /// Each byte is the low byte of a fresh 64-bit value, ensuring cross-platform
    /// test vector compatibility.
    /// </summary>
    public byte[] RandomData(int size)
    {
        ArgumentOutOfRangeException.ThrowIfNegative(size);

        var data = new byte[size];
        for (int i = 0; i < size; i++)
            data[i] = (byte)NextUInt64();
        return data;
    }

    public void FillRandomData(Span<byte> data)
    {
        for (int i = 0; i < data.Length; i++)
            data[i] = (byte)NextUInt64();
    }

    /// <summary>
    /// Creates a seeded random number generator with a fixed seed.
    /// </summary>
    /// <returns>A new <see cref="SeededRandomNumberGenerator"/> initialized with a fixed seed.</returns>
    public static SeededRandomNumberGenerator CreateFake() => new(FakeSeed);

    /// <summary>
    /// Creates an array of random data with a fixed seed.
    /// </summary>
    /// <param name="size">The number of random bytes to generate.</param>
    /// <returns>An array containing <paramref name="size"/> deterministic random bytes.</returns>
    public static byte[] FakeRandomData(int size) => CreateFake().RandomData(size);
}
