using System.Buffers.Binary;

namespace BlockchainCommons.BCRand;

/// <summary>
/// A deterministic pseudo-random number generator for testing purposes.
/// Uses Xoshiro256** internally. Not cryptographically secure.
/// </summary>
public sealed class SeededRandomNumberGenerator : IRandomNumberGenerator
{
    private static readonly ulong[] FakeSeed =
    [
        17295166580085024720,
        422929670265678780,
        5577237070365765850,
        7953171132032326923
    ];

    private readonly Xoshiro256StarStar _rng;

    /// <summary>
    /// Creates a new seeded random number generator.
    /// The seed must contain exactly 4 unsigned 64-bit integers.
    /// </summary>
    public SeededRandomNumberGenerator(ulong[] seed)
    {
        if (seed.Length != 4)
            throw new ArgumentException("Seed must contain exactly 4 elements.", nameof(seed));

        Span<byte> seedBytes = stackalloc byte[32];
        for (int i = 0; i < 4; i++)
            BinaryPrimitives.WriteUInt64LittleEndian(seedBytes.Slice(i * 8, 8), seed[i]);

        _rng = new Xoshiro256StarStar(seedBytes);
    }

    public uint NextUInt32() => (uint)NextUInt64();

    public ulong NextUInt64() => _rng.NextUInt64();

    /// <summary>
    /// Returns an array of random bytes, generated byte-by-byte from NextUInt64().
    /// Each byte is the low byte of a fresh 64-bit value, ensuring cross-platform
    /// test vector compatibility.
    /// </summary>
    public byte[] RandomData(int size)
    {
        var data = new byte[size];
        for (int i = 0; i < size; i++)
            data[i] = (byte)NextUInt64();
        return data;
    }

    public void FillRandomData(Span<byte> data)
    {
        for (int i = 0; i < data.Length; i++)
            data[i] = (byte)NextUInt64();
    }

    /// <summary>Creates a seeded RNG with a fixed seed for deterministic testing.</summary>
    public static SeededRandomNumberGenerator CreateFake() => new(FakeSeed);

    /// <summary>Creates deterministic random data from a fixed seed.</summary>
    public static byte[] FakeRandomData(int size) => CreateFake().RandomData(size);
}
