"""Public constants for the SSKR package."""

from bc_shamir import MAX_SECRET_LEN, MAX_SHARE_COUNT, MIN_SECRET_LEN

MAX_GROUPS_COUNT = MAX_SHARE_COUNT
METADATA_SIZE_BYTES = 5
MIN_SERIALIZE_SIZE_BYTES = METADATA_SIZE_BYTES + MIN_SECRET_LEN

__all__ = [
    "MAX_GROUPS_COUNT",
    "MAX_SECRET_LEN",
    "MAX_SHARE_COUNT",
    "METADATA_SIZE_BYTES",
    "MIN_SECRET_LEN",
    "MIN_SERIALIZE_SIZE_BYTES",
]
