#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LOG_FILE="$ROOT_DIR/LOG.md"
OUT_FILE="$ROOT_DIR/FLUENCY_NEEDED.md"

if [[ ! -f "$LOG_FILE" ]]; then
  echo "ERROR: missing $LOG_FILE" >&2
  exit 1
fi

pending_tmp="$(mktemp)"
trap 'rm -f "$pending_tmp"' EXIT

awk -F'|' '
function trim(s) {
  gsub(/^[ \t]+|[ \t]+$/, "", s)
  return s
}

function normalized_task(t, t2) {
  t2 = tolower(trim(t))
  if (t2 == "translation") return "Translation"
  if (t2 == "fluency") return "Fluency"
  return trim(t)
}

/^\|/ {
  date = trim($2)
  crate = trim($3)
  version = trim($4)
  language = trim($5)
  package = trim($6)
  model = trim($7)
  task = normalized_task($8)

  if (date == "" || date == "Date" || date ~ /^-+$/) next

  key = crate "|" version "|" language "|" package

  if (task == "Translation") {
    translation_seen[key] = 1
    if (!(key in translation_model)) {
      translation_model[key] = model
    }
  }

  if (task == "Fluency") {
    fluency_seen[key] = 1
    fluency_models[key, model] = 1
  }
}

END {
  for (key in translation_seen) {
    has_cross_model_fluency = 0
    for (pair in fluency_models) {
      split(pair, parts, SUBSEP)
      if (parts[1] == key && parts[2] != translation_model[key]) {
        has_cross_model_fluency = 1
        break
      }
    }

    if (!has_cross_model_fluency) {
      reason = fluency_seen[key] ? "Fluency logged, but only by the translation model" : "No fluency pass logged"

      split(key, fields, "|")
      original_model = translation_model[key]
      if (original_model ~ /Claude/) {
        recommended_model = "📖 GPT Codex"
      } else if (original_model ~ /GPT/) {
        recommended_model = "🎻 Claude Opus"
      } else {
        recommended_model = "Any different model"
      }

      printf "%s|%s|%s|%s|%s|%s|%s\n", \
        fields[1], fields[2], fields[3], fields[4], original_model, recommended_model, reason
    }
  }
}
' "$LOG_FILE" | sort > "$pending_tmp"

total_targets="$(awk -F'|' '
function trim(s) {
  gsub(/^[ \t]+|[ \t]+$/, "", s)
  return s
}

/^\|/ {
  date = trim($2)
  crate = trim($3)
  version = trim($4)
  language = trim($5)
  package = trim($6)
  task = tolower(trim($8))

  if (date == "" || date == "Date" || date ~ /^-+$/) next
  if (task == "translation") {
    key = crate "|" version "|" language "|" package
    seen[key] = 1
  }
}

END {
  count = 0
  for (k in seen) count++
  print count
}
' "$LOG_FILE")"

pending_targets="$(wc -l < "$pending_tmp" | tr -d '[:space:]')"

cross_checked_targets=$((total_targets - pending_targets))
updated_on="$(date +%F)"

{
  echo "# Fluency Cross-Checks Needed"
  echo
  echo "Running queue of translated targets that still need at least one fluency pass by a model different from the original translation model."
  echo
  echo "Generated from \`LOG.md\` by \`scripts/update-fluency-needed.sh\`."
  echo
  echo "- Last updated: $updated_on"
  echo "- Targets translated: $total_targets"
  echo "- Targets with cross-model fluency complete: $cross_checked_targets"
  echo "- Targets still needing cross-model fluency: $pending_targets"
  echo
  if [[ "$pending_targets" -eq 0 ]]; then
    echo "All translated targets have a cross-model fluency pass."
  else
    echo "| Crate | Version | Language | Package | Model To Avoid (Original Translation) | Recommended Cross-Check Model | Pending Reason |"
    echo "|-------|---------|----------|---------|----------------------------------------|--------------------------------|----------------|"

    while IFS='|' read -r crate version language package original_model recommended_model reason; do
      echo "| $crate | $version | $language | $package | $original_model | $recommended_model | $reason |"
    done < "$pending_tmp"
  fi
  echo
  echo "## Update Rule"
  echo
  echo "- After appending any \`Translation\` or \`Fluency\` row to \`LOG.md\`, run \`bash scripts/update-fluency-needed.sh\`."
  echo "- Do not edit this file by hand unless the script itself is being corrected."
} > "$OUT_FILE"
