/**
 * Known Values: A compact, deterministic representation for ontological
 * concepts.
 *
 * This package implements the Blockchain Commons Known Values specification,
 * providing a compact way to represent ontological concepts using 64-bit
 * unsigned integers with optional human-readable names.
 *
 * @module @bc/known-values
 */

export { KnownValue } from './known-value.js';
export { KnownValuesStore } from './known-values-store.js';

// Registry constants and global store
export {
    // Global store
    KNOWN_VALUES,

    // General (0–27)
    UNIT_RAW, UNIT,
    IS_A_RAW, IS_A,
    ID_RAW, ID,
    SIGNED_RAW, SIGNED,
    NOTE_RAW, NOTE,
    HAS_RECIPIENT_RAW, HAS_RECIPIENT,
    SSKR_SHARE_RAW, SSKR_SHARE,
    CONTROLLER_RAW, CONTROLLER,
    KEY_RAW, KEY,
    DEREFERENCE_VIA_RAW, DEREFERENCE_VIA,
    ENTITY_RAW, ENTITY,
    NAME_RAW, NAME,
    LANGUAGE_RAW, LANGUAGE,
    ISSUER_RAW, ISSUER,
    HOLDER_RAW, HOLDER,
    SALT_RAW, SALT,
    DATE_RAW, DATE,
    UNKNOWN_VALUE_RAW, UNKNOWN_VALUE,
    VERSION_VALUE_RAW, VERSION_VALUE,
    HAS_SECRET_RAW, HAS_SECRET,
    DIFF_EDITS_RAW, DIFF_EDITS,
    VALID_FROM_RAW, VALID_FROM,
    VALID_UNTIL_RAW, VALID_UNTIL,
    POSITION_RAW, POSITION,
    NICKNAME_RAW, NICKNAME,
    VALUE_RAW, VALUE,
    ATTESTATION_RAW, ATTESTATION,
    VERIFIABLE_AT_RAW, VERIFIABLE_AT,

    // Attachments (50–52)
    ATTACHMENT_RAW, ATTACHMENT,
    VENDOR_RAW, VENDOR,
    CONFORMS_TO_RAW, CONFORMS_TO,

    // XID Documents (60–68)
    ALLOW_RAW, ALLOW,
    DENY_RAW, DENY,
    ENDPOINT_RAW, ENDPOINT,
    DELEGATE_RAW, DELEGATE,
    PROVENANCE_RAW, PROVENANCE,
    PRIVATE_KEY_RAW, PRIVATE_KEY,
    SERVICE_RAW, SERVICE,
    CAPABILITY_RAW, CAPABILITY,
    PROVENANCE_GENERATOR_RAW, PROVENANCE_GENERATOR,

    // XID Privileges (70–86)
    PRIVILEGE_ALL_RAW, PRIVILEGE_ALL,
    PRIVILEGE_AUTH_RAW, PRIVILEGE_AUTH,
    PRIVILEGE_SIGN_RAW, PRIVILEGE_SIGN,
    PRIVILEGE_ENCRYPT_RAW, PRIVILEGE_ENCRYPT,
    PRIVILEGE_ELIDE_RAW, PRIVILEGE_ELIDE,
    PRIVILEGE_ISSUE_RAW, PRIVILEGE_ISSUE,
    PRIVILEGE_ACCESS_RAW, PRIVILEGE_ACCESS,
    PRIVILEGE_DELEGATE_RAW, PRIVILEGE_DELEGATE,
    PRIVILEGE_VERIFY_RAW, PRIVILEGE_VERIFY,
    PRIVILEGE_UPDATE_RAW, PRIVILEGE_UPDATE,
    PRIVILEGE_TRANSFER_RAW, PRIVILEGE_TRANSFER,
    PRIVILEGE_ELECT_RAW, PRIVILEGE_ELECT,
    PRIVILEGE_BURN_RAW, PRIVILEGE_BURN,
    PRIVILEGE_REVOKE_RAW, PRIVILEGE_REVOKE,

    // Expression and Function Calls (100–108)
    BODY_RAW, BODY,
    RESULT_RAW, RESULT,
    ERROR_RAW, ERROR,
    OK_VALUE_RAW, OK_VALUE,
    PROCESSING_VALUE_RAW, PROCESSING_VALUE,
    SENDER_RAW, SENDER,
    SENDER_CONTINUATION_RAW, SENDER_CONTINUATION,
    RECIPIENT_CONTINUATION_RAW, RECIPIENT_CONTINUATION,
    CONTENT_RAW, CONTENT,

    // Cryptography (200–203)
    SEED_TYPE_RAW, SEED_TYPE,
    PRIVATE_KEY_TYPE_RAW, PRIVATE_KEY_TYPE,
    PUBLIC_KEY_TYPE_RAW, PUBLIC_KEY_TYPE,
    MASTER_KEY_TYPE_RAW, MASTER_KEY_TYPE,

    // Cryptocurrency Assets (300–303)
    ASSET_RAW, ASSET,
    BITCOIN_VALUE_RAW, BITCOIN_VALUE,
    ETHEREUM_VALUE_RAW, ETHEREUM_VALUE,
    TEZOS_VALUE_RAW, TEZOS_VALUE,

    // Cryptocurrency Networks (400–402)
    NETWORK_RAW, NETWORK,
    MAIN_NET_VALUE_RAW, MAIN_NET_VALUE,
    TEST_NET_VALUE_RAW, TEST_NET_VALUE,

    // Bitcoin (500–508)
    BIP32_KEY_TYPE_RAW, BIP32_KEY_TYPE,
    CHAIN_CODE_RAW, CHAIN_CODE,
    DERIVATION_PATH_TYPE_RAW, DERIVATION_PATH_TYPE,
    PARENT_PATH_RAW, PARENT_PATH,
    CHILDREN_PATH_RAW, CHILDREN_PATH,
    PARENT_FINGERPRINT_RAW, PARENT_FINGERPRINT,
    PSBT_TYPE_RAW, PSBT_TYPE,
    OUTPUT_DESCRIPTOR_TYPE_RAW, OUTPUT_DESCRIPTOR_TYPE,
    OUTPUT_DESCRIPTOR_RAW, OUTPUT_DESCRIPTOR,

    // Graphs (600–613, 700–706)
    GRAPH_RAW, GRAPH,
    SOURCE_TARGET_GRAPH_RAW, SOURCE_TARGET_GRAPH,
    PARENT_CHILD_GRAPH_RAW, PARENT_CHILD_GRAPH,
    DIGRAPH_RAW, DIGRAPH,
    ACYCLIC_GRAPH_RAW, ACYCLIC_GRAPH,
    MULTIGRAPH_RAW, MULTIGRAPH,
    PSEUDOGRAPH_RAW, PSEUDOGRAPH,
    GRAPH_FRAGMENT_RAW, GRAPH_FRAGMENT,
    DAG_RAW, DAG,
    TREE_RAW, TREE,
    FOREST_RAW, FOREST,
    COMPOUND_GRAPH_RAW, COMPOUND_GRAPH,
    HYPERGRAPH_RAW, HYPERGRAPH,
    DIHYPERGRAPH_RAW, DIHYPERGRAPH,
    NODE_RAW, NODE,
    EDGE_RAW, EDGE,
    SOURCE_RAW, SOURCE,
    TARGET_RAW, TARGET,
    PARENT_RAW, PARENT,
    CHILD_RAW, CHILD,
    SELF_RAW, SELF,
} from './known-values-registry.js';

// Directory loading
export {
    type RegistryEntry,
    type OntologyInfo,
    type GeneratedInfo,
    type RegistryFile,
    LoadError,
    LoadResult,
    DirectoryConfig,
    ConfigError,
    loadFromDirectory,
    loadFromConfig,
    setDirectoryConfig,
    addSearchPaths,
} from './directory-loader.js';
